export const A = {
  // UI
  LOADING: 'LOADING',
  WRITING: 'WRITING',
  SHOW_MENU: 'SHOW_MENU',
  HIDE_MENU: 'HIDE_MENU',

  // Navigate
  NEXT: 'NEXT',
  PREV: 'PREV',
  REWIND: 'REWIND',
  PLAY: 'PLAY',
  STOP: 'STOP',
  PLAY_STOP: 'PLAY_STOP',

  // Set current
  SET_PEN: 'SET_PEN',
  SET_STEP: 'SET_STEP',
  SET_STEP_CODE: 'SET_STEP_CODE',
  SET_STEP_INFO: 'SET_STEP_INFO',

  // Create or edit new ones
  NEW_STEP: 'NEW_STEP',
  DELETE_STEP: 'DELETE_STEP',
  UPDATE_STEP: 'UPDATE_STEP',
}
